import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { database } from '../src/database/database';

export default function CheckinScreen() {
  const [mood, setMood] = useState(3); const [energy, setEnergy] = useState(5); const [stress, setStress] = useState(5); const [concentration, setConcentration] = useState(5); const [notes, setNotes] = useState('');
  function save() { database.runSync('INSERT INTO checkins (mood, energy, stress, concentration, checked_at, notes) VALUES (?, ?, ?, ?, ?, ?)', [mood, energy, stress, concentration, new Date().toISOString(), notes.trim() || null]); Alert.alert('Gespeichert', 'Dein Check-in wurde gespeichert.', [{ text: 'OK', onPress: () => router.back() }]); }
  return <ScrollView contentContainerStyle={styles.container}><Text style={styles.title}>Wie geht es dir?</Text><Text style={styles.heading}>Stimmung</Text><View style={styles.moods}>{['😣','🙁','😐','🙂','😄'].map((icon, index) => <Pressable key={icon} onPress={() => setMood(index + 1)} style={[styles.mood, mood === index + 1 && styles.selected]}><Text style={styles.icon}>{icon}</Text></Pressable>)}</View><Scale label="Energie" value={energy} setValue={setEnergy} /><Scale label="Stress" value={stress} setValue={setStress} /><Scale label="Konzentration" value={concentration} setValue={setConcentration} /><TextInput value={notes} onChangeText={setNotes} placeholder="Was beeinflusst dich heute?" multiline style={styles.notes} /><Pressable style={styles.save} onPress={save}><Text style={styles.saveText}>Check-in speichern</Text></Pressable></ScrollView>;
}
function Scale({ label, value, setValue }: { label: string; value: number; setValue: (v: number) => void }) { return <View style={styles.scale}><View style={styles.scaleHeader}><Text style={styles.heading}>{label}</Text><Text style={styles.value}>{value}/10</Text></View><View style={styles.numbers}>{Array.from({ length: 10 }, (_, i) => i + 1).map(n => <Pressable key={n} onPress={() => setValue(n)} style={[styles.number, value === n && styles.numberSelected]}><Text style={value === n && styles.numberTextSelected}>{n}</Text></Pressable>)}</View></View>; }
const styles = StyleSheet.create({ container: { padding: 22, paddingBottom: 50, backgroundColor: '#F5F3EC' }, title: { fontSize: 28, fontWeight: '800', color: '#27352F', marginBottom: 24 }, heading: { fontSize: 16, fontWeight: '800', color: '#39473F' }, moods: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 12, marginBottom: 26 }, mood: { width: 55, height: 55, borderRadius: 17, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' }, selected: { borderWidth: 3, borderColor: '#27352F' }, icon: { fontSize: 27 }, scale: { marginBottom: 23 }, scaleHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 }, value: { fontWeight: '800', color: '#27352F' }, numbers: { flexDirection: 'row', justifyContent: 'space-between' }, number: { width: 30, height: 38, backgroundColor: '#FFFFFF', borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, numberSelected: { backgroundColor: '#27352F' }, numberTextSelected: { color: '#FFFFFF', fontWeight: '800' }, notes: { minHeight: 100, borderRadius: 15, backgroundColor: '#FFFFFF', padding: 14, textAlignVertical: 'top' }, save: { minHeight: 56, borderRadius: 17, backgroundColor: '#27352F', alignItems: 'center', justifyContent: 'center', marginTop: 20 }, saveText: { color: '#FFFFFF', fontWeight: '800', fontSize: 16 } });
