import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { database } from '../src/database/database';

const symptomOptions = ['Blähbauch', 'Übelkeit', 'Bauchschmerzen', 'Kopfschmerzen', 'Schwindel', 'Herzklopfen', 'Nase verstopft', 'Husten/Schleim', 'Hautreaktion', 'Müdigkeit', 'Schlafprobleme', 'Innere Unruhe'];

export default function SymptomsScreen() {
  const [selected, setSelected] = useState<string[]>([]); const [severity, setSeverity] = useState(5); const [notes, setNotes] = useState('');
  function toggle(name: string) { setSelected(current => current.includes(name) ? current.filter(item => item !== name) : [...current, name]); }
  function save() { if (!selected.length) { Alert.alert('Symptom fehlt', 'Bitte mindestens ein Symptom auswählen.'); return; } const now = new Date().toISOString(); database.withTransactionSync(() => selected.forEach(name => database.runSync('INSERT INTO symptoms (symptom_name, severity, started_at, notes) VALUES (?, ?, ?, ?)', [name, severity, now, notes.trim() || null]))); Alert.alert('Gespeichert', 'Deine Symptome wurden dokumentiert.', [{ text: 'OK', onPress: () => router.back() }]); }
  return <ScrollView contentContainerStyle={styles.container}><Text style={styles.title}>Was bemerkst du?</Text><View style={styles.chips}>{symptomOptions.map(name => <Pressable key={name} onPress={() => toggle(name)} style={[styles.chip, selected.includes(name) && styles.chipSelected]}><Text style={[styles.chipText, selected.includes(name) && styles.chipTextSelected]}>{name}</Text></Pressable>)}</View><View style={styles.scaleHeader}><Text style={styles.heading}>Stärke</Text><Text style={styles.value}>{severity}/10</Text></View><View style={styles.numbers}>{Array.from({ length: 10 }, (_, i) => i + 1).map(n => <Pressable key={n} onPress={() => setSeverity(n)} style={[styles.number, severity === n && styles.numberSelected]}><Text style={severity === n && styles.numberTextSelected}>{n}</Text></Pressable>)}</View><TextInput value={notes} onChangeText={setNotes} placeholder="Wann begann es? Was hast du davor gegessen?" multiline style={styles.notes} /><Pressable style={styles.save} onPress={save}><Text style={styles.saveText}>Symptome speichern</Text></Pressable></ScrollView>;
}
const styles = StyleSheet.create({ container: { padding: 22, paddingBottom: 50, backgroundColor: '#F5F3EC' }, title: { fontSize: 28, fontWeight: '800', color: '#27352F', marginBottom: 20 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 9, marginBottom: 28 }, chip: { backgroundColor: '#FFFFFF', borderRadius: 999, paddingHorizontal: 14, paddingVertical: 11 }, chipSelected: { backgroundColor: '#27352F' }, chipText: { color: '#445149', fontWeight: '600' }, chipTextSelected: { color: '#FFFFFF' }, scaleHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 }, heading: { fontSize: 17, fontWeight: '800', color: '#39473F' }, value: { fontWeight: '800', color: '#27352F' }, numbers: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 24 }, number: { width: 30, height: 38, backgroundColor: '#FFFFFF', borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, numberSelected: { backgroundColor: '#27352F' }, numberTextSelected: { color: '#FFFFFF', fontWeight: '800' }, notes: { minHeight: 105, borderRadius: 15, backgroundColor: '#FFFFFF', padding: 14, textAlignVertical: 'top' }, save: { minHeight: 56, borderRadius: 17, backgroundColor: '#27352F', alignItems: 'center', justifyContent: 'center', marginTop: 20 }, saveText: { color: '#FFFFFF', fontWeight: '800', fontSize: 16 } });
